services:

  postgres:
    image: postgres:17

    container_name: echo-dev-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: echo_db
      POSTGRES_USER: echo_user
      POSTGRES_PASSWORD: Echo@1

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: