services:
  postgres:
    image: postgres:17

    container_name: echo-dev-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: echo_db
      POSTGRES_USER: echo_user
      POSTGRES_PASSWORD: Echo@1

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: echo-dev-backend

    env_file:
      - ./backend/.env

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    volumes:
      - "D:/Echostorage:/storage"
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data: