services:

  postgres:
    image: postgres:17

    container_name: echo-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: echo_db
      POSTGRES_USER: echo_user
      POSTGRES_PASSWORD: Echo@1

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - echo-network

backend:
  build:
    context: .
    dockerfile: backend/Dockerfile

  container_name: echo-backend

  restart: unless-stopped

  env_file:
    - ./backend/.env

  depends_on:
    - postgres

  volumes:
    - /srv/echo-storage:/srv/echo-storage
    - /var/run/docker.sock:/var/run/docker.sock

  ports:
    - "3000:3000"

  networks:
    - echo-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_URL: https://api.devpiyush.in

    container_name: echo-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "8080:80"

    networks:
      - echo-network

volumes:
  postgres_data:

networks:
  echo-network: