const express = require("express");
const router = express.Router();
const projectRoutes = require("./project.routes");
const webhookRoutes = require("./webhook.routes");
const authRoutes = require("./auth.routes");
const fileRoutes = require("./file.routes");
const environmentRoutes = require("./environment.routes");
const applicationRoutes = require("./application.routes");
const deploymentRoutes = require("./deployment.routes");
const gitRoutes = require("./git.routes");
const projectSettingsRoutes = require("./projectSettings.routes");
const serverRoutes = require("./server.routes");
const dashboardRoutes = require("./dashboard.routes");
const adminRoutes = require("./admin.routes");
const storageRoutes = require("./storage.routes");
const cloudRoutes = require("./cloud.routes");

router.use("/webhooks", webhookRoutes);
router.use("/auth", authRoutes);
router.use("/projects", projectRoutes);
router.use("/", fileRoutes);
router.use(environmentRoutes);
router.use(applicationRoutes);
router.use("/", deploymentRoutes);
router.use(gitRoutes);
router.use(projectSettingsRoutes);
router.use("/server", serverRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/admin", adminRoutes);
router.use("/storage", storageRoutes);
router.use("/cloud", cloudRoutes);

module.exports = router;
