name: Deploy Echo Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update repository
        run: |
          cd /srv/echo
          git pull --ff-only

      - name: Restart containers
        run: |
          docker compose \
             -f /srv/echo/docker-compose.prod.yml \
             --project-directory /srv/echo \
             up -d --build
